merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bands/', views.band_list, name='band-list'),
    path('bands/<int:id>/', views.band_detail, name='band-detail'),
    path('about-us/', views.about),
    path('list/', views.listings),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Band(models.Model):

    class Genre(models.TextChoices):
        ROCK = 'ROCK', 'Rock'
        POP = 'POP', 'Pop'
        JAZZ = 'JAZZ', 'Jazz'
        CLASSICAL = 'CLASSICAL', 'Classical'
        HIP_HOP = 'HIP_HOP', 'Hip Hop'
        ELECTRONIC = 'ELECTRONIC', 'Electronic'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=20, default=Genre.ROCK)
    biography = models.fields.CharField(max_length=1000, default='No biography provided')
    year_formed = models.fields.IntegerField(
        default=2021,
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)


class Listing(models.Model):
    title = models.fields.CharField(max_length=100)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)
  

merchex/listings/views.py
from django.http import HttpResponse
from django.shortcuts import render
from listings.models import Band
from listings.models import Listing


def band_list(request):
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})


def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                   {'band' : band})


def about(request):
    return HttpResponse('<h1>À propos</h1> <p>Nous adorons merch !</p>')


def listings(request):
    listings = Listing.objects.all()
    return HttpResponse(f"""
        <h1>Hello Django!</h1>
        <p>Mes groupes préférés sont :</p>
        <ul>
            <li>{listings[0].title}</li>
            <li>{listings[1].title}</li>
            <li>{listings[2].title}</li>
            <li>{listings[3].title}</li>
        </ul>
        """)

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>{{ band.name }}</h2>

<ul>
 <li>Genre : {{ band.get_genre_display }}</li>
 <li>Année de formation : {{ band.year_formed }}</li>
 <li>Actif : {{ band.active }}</li>
 <li>{{ band.official_homepage }}</li>
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-list' %}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<ul>
 {% for band in bands %}
  <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
 {% endfor %}
</ul>

{% endblock %}

merchex/listings/templates/listings/base.html
<html>
    <head><title>Merchex</title></head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
    </nav>

        {% block content %}{% endblock %}

    </body>
    
</html>